---
collections:
  blog:
    output: true
    permalink: /:collection/:name/

exclude:
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock
  - Justfile
  - bin/
  - vendor/

url: https://cbjohnson.info
