---
name: Setup Vale
description: Installs the Vale linter

inputs:
  version:
    description: Version
    required: true

  arch:
    description: Architecture
    required: false
    default: Linux_64-bit

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo curl --location --silent "https://github.com/errata-ai/vale/releases/download/v${{ inputs.version }}/vale_${{ inputs.version }}_${{ inputs.arch }}.tar.gz" \
        | tar --extract --gunzip vale \
        && mv vale /usr/local/bin/vale
