---
name: Setup Just
description: Installs the Just task runner

inputs:
  version:
    description: Version
    required: true

  arch:
    description: Architecture
    required: false
    default: x86_64-unknown-linux-musl

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo curl --location --silent "https://github.com/casey/just/releases/download/${{ inputs.version }}/just-${{ inputs.version }}-${{ inputs.arch }}.tar.gz" \
        | tar --extract --gunzip just \
        && mv just /usr/local/bin/just
