---
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      vale: '2.15.4'
      ruby: '3.1'
      node: '16'

    steps:
      - uses: actions/checkout@v3

      - id: cache-vale
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/vale
          key: setup-vale-cache-${{ runner.os }}-${{ env.vale }}

      - if: steps.cache-vale.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-vale
        with:
          version: ${{ env.vale }}

      - uses: extractions/setup-just@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}

      - run: just lint
      - run: just test
      - run: just generate
