---
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      just: 0.10.4
      vale: 2.13.0
      ruby: 3.0
      node: 16

    steps:
      - uses: actions/checkout@v2

      - id: cache-just
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/just
          key: ${{ runner.os }}-${{ env.just }}

      - id: cache-vale
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/vale
          key: ${{ runner.os }}-${{ env.vale }}

      - if: steps.cache-just.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-just
        with:
          version: ${{ env.just }}

      - if: steps.cache-vale.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-vale
        with:
          version: ${{ env.vale }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}

      - run: just lint
      - run: just test
      - run: just generate
