---
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      node: '18'
      ruby: '3.2'
      vale: '2.22.0'

    steps:
      - uses: actions/checkout@v3

      - uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/errata-ai/vale/releases/download/v${{ env.vale }}/vale_${{ env.vale }}_Linux_64-bit.tar.gz
          name: vale
          version: ${{ env.vale }}

      - uses: extractions/setup-just@v1

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.ruby }}

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.node }}

      - run: just lint
      - run: just test
      - run: just generate
