---
name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy to
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ruby: 3.0

    steps:
      - uses: actions/checkout@v2

      - uses: extractions/setup-just@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true

      - run: just generate
        env:
          SSG_ENV: production

      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: ${{ github.event.inputs.branch }}
          folder: _site
